spring:
  #数据源useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
  datasource:
    url: jdbc:mysql://192.168.0.48:3306/tax-dev?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false&useUnicode=true&autoReconnect=true&rewriteBatchedStatements=true
    username: mihuo
    password: Mihuo@0908
    driver-class-name: com.mysql.jdbc.Driver

#mybatis配置
#mybatis:
#  typeAliasesPackage: com.example.demo.entity
#  mapperLocations: classpath:mapper/*.xml
#  configLocation: classpath:/mybatis-config.xml

mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.demo.entity
  global-config:
    id-type: 0
    field-strategy: 2
    capital-mode: true
    refresh-mapper: true

#  configuration:
#    map-underscore-to-camel-case: true